spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rungroupcourse
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
